# Generated by Django 4.0.4 on 2024-03-29 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_company_remove_customuser_job_title_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.employee'),
        ),
    ]
