# Generated by Django 4.0.4 on 2024-03-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_customuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
