# Generated by Django 4.0.4 on 2024-03-30 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_customuser_job_title_alter_asset_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.customuser'),
        ),
    ]
